app:
    resource: '@AppBundle/Controller'

product_delete:
      path: /product/delete/{id}
      defaults:  { _controller: AppBundle:Product:delete }
      methods:  [GET, HEAD]

product_store:
          path: /product
          defaults: {_controller: AppBundle:Product:store}
          methods: [POST]

product_create:
            path: /product/create
            defaults: {_controller: AppBundle:Product:create}
            methods: [GET]

product_index:
          path: /product/
          defaults: { _controller: AppBundle:Product:index }
          methods: [GET]

product_edit:
          path: /product/{id}/edit
          defaults: {_controller:  AppBundle:Product:edit}
          methods: [GET]

product_update:
          path: /product/{id}
          defaults: {_controller:  AppBundle:Product:update}
          methods: [POST]